apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  serviceName: proxy-server-headless
  replicas: 2
  selector:
    matchLabels:
      app: proxy-server
  template:
    metadata:
      labels:
        app: proxy-server
    spec:
      containers:
      - name: proxy-server
        image: <your-dockerhub-username>/proxy-server:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: certs
          mountPath: /app/certs
        # 设置环境变量 (可选)
        env:
        - name: CERT_PATH
          value: "/app/certs/server.crt"
        - name: KEY_PATH
          value: "/app/certs/server.key"
      volumes:
      - name: certs
        secret:
          secretName: proxy-server-certificates