apiVersion: v1
kind: Service
metadata:
  name: proxy-server
  labels:
    app: proxy-server
spec:
  type: ClusterIP
  selector:
    app: proxy-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080